import type { Metadata } from "next";
import "./globals.css";
import { GeistPixelSquare } from "geist/font/pixel";

export const metadata: Metadata = {
  title: "PosterZZZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children : React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistPixelSquare.variable} h-full`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
